--- #YAML:1.0
name:               Template-Plugin-Filter-Minify-JavaScript-XS
version:            0.91
abstract:           JavaScript::Minifier::XS filter for Template Toolkit
author:
    - Michael Schout <mschout@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    JavaScript::Minifier::XS:  0
    Template:             2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
